FROM frrouting/frr:latest

USER root

RUN apk add --no-cache \
        tcpdump \
        iputils \
        traceroute \
        busybox-extras \
        procps \
        curl \
        vim \
        less

#USER frr
